# 📘 NumPy Implementation Examples
This notebook covers basic to intermediate concepts of NumPy.

In [21]:
import numpy as np


## 1. Array Creation

In [28]:

# Creating arrays
a = np.array([1, 2, 3, 4, 5])
b = np.zeros((2,3))
c = np.ones((3,3))
d = np.arange(0, 10, 2)
e = np.linspace(0, 1, 5)

print("Array a:", a)
print("Zeros array:", b)
print("Ones array:", c)
print("Arange:", d)
print("Linspace:", e)


Array a: [1 2 3 4 5]
Zeros array: [[0. 0. 0.]
 [0. 0. 0.]]
Ones array: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


## 2. Array Operations

In [23]:

x = np.array([10, 20, 30, 40])
y = np.array([1, 2, 3, 4])

print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)
print("Power:", x ** 2)


Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Power: [ 100  400  900 1600]


## 3. Indexing & Slicing

In [24]:

arr = np.array([10, 20, 30, 40, 50])
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice [1:4]:", arr[1:4])
print("Every 2nd element:", arr[::2])


First element: 10
Last element: 50
Slice [1:4]: [20 30 40]
Every 2nd element: [10 30 50]


## 4. Mathematical Functions

In [25]:

arr = np.array([1, 2, 3, 4, 5])
print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Sine:", np.sin(arr))
print("Log:", np.log(arr))


Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


## 5. Reshaping Arrays

In [26]:

arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print("Original:", arr)
print("Reshaped (3x4):", reshaped)


Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3x4): [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 6. Aggregations

In [27]:

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Column-wise sum:", np.sum(arr, axis=0))
print("Row-wise sum:", np.sum(arr, axis=1))


Sum: 45
Mean: 5.0
Standard Deviation: 2.581988897471611
Max: 9
Min: 1
Column-wise sum: [12 15 18]
Row-wise sum: [ 6 15 24]
